export const GET_CURRENT_STATE = "GET_CURRENT_STATE"

export const AUTHENTICATION_REQUEST = "AUTHENTICATION_REQUEST"
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS"

export const SET_CURRENT_USER_DETAILS_REQUEST = "SET_CURRENT_USER_DETAILS_REQUEST"
export const SET_CURRENT_USER_DETAILS_SUCCESS = "SET_CURRENT_USER_DETAILS_SUCCESS"